/**
 * API Storage — Write operations for ideas and projects.
 *
 * Handles creation of markdown files and registry updates for both
 * idea ingestion (from slop-planner) and project uploads (from slop-builder).
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import path from 'path';

/**
 * Generate a markdown app file from idea JSON and write it to the apps directory.
 *
 * @param {object} idea — { name, slug, overview, problemSolved, targetAudience, keyFeatures, monetization, techStack, implementationPlan, dateAdded }
 * @param {string} appsDir — Absolute path to the apps directory
 * @returns {string} — The written file path
 */
function writeAppFile(idea, appsDir) {
  mkdirSync(appsDir, { recursive: true });

  const lines = [];
  lines.push(`# ${idea.name}`);
  lines.push('');
  lines.push('## Overview');
  lines.push(idea.overview || '');
  lines.push('');
  lines.push('## Problem Solved');
  lines.push(idea.problemSolved || '');
  lines.push('');
  lines.push('## Target Audience');
  for (const item of (idea.targetAudience || [])) {
    lines.push(`- ${item}`);
  }
  lines.push('');
  lines.push('## Key Features');
  let featNum = 1;
  for (const feat of (idea.keyFeatures || [])) {
    const title = typeof feat === 'string' ? feat : feat.title;
    const desc = typeof feat === 'string' ? '' : feat.description;
    if (desc) {
      lines.push(`${featNum}. **${title}**: ${desc}`);
    } else {
      lines.push(`${featNum}. **${title}**`);
    }
    featNum++;
  }
  lines.push('');
  lines.push('## Monetization Strategy');
  for (const item of (idea.monetization || [])) {
    lines.push(`- ${item}`);
  }
  lines.push('');
  lines.push('## Tech Stack Suggestions');
  if (idea.techStack && typeof idea.techStack === 'object') {
    for (const [key, value] of Object.entries(idea.techStack)) {
      const label = key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
      lines.push(`- **${label}**: ${value}`);
    }
  }
  lines.push('');
  lines.push('## Implementation Plan');
  lines.push(idea.implementationPlan || 'See plan for details.');
  lines.push('');
  lines.push('## Status');
  lines.push('- [ ] Idea Generated');
  lines.push('- [ ] Plan Created');
  lines.push('- [ ] Development Started');
  lines.push('- [ ] MVP Complete');
  lines.push('- [ ] Launched');
  lines.push('');
  lines.push('---');
  lines.push(`*Generated by Slop Planner on ${idea.dateAdded || new Date().toISOString().split('T')[0]}*`);
  lines.push('');

  const filePath = path.join(appsDir, `${idea.slug}.md`);
  writeFileSync(filePath, lines.join('\n'));
  return filePath;
}

/**
 * Append a new idea entry to the API's own db.md.
 * Auto-increments the idea number and updates the total count.
 *
 * @param {object} idea — { name, slug, category, dateAdded }
 * @param {string} dataDir — Absolute path to the data directory
 * @param {string} dbPath — Absolute path to db.md
 * @param {Function} parseDatabase — Parser function for existing entries
 */
function appendToDatabase(idea, dataDir, dbPath, parseDatabase) {
  mkdirSync(dataDir, { recursive: true });

  const existing = parseDatabase(dbPath);
  const nextId = existing.length > 0
    ? Math.max(...existing.map(e => e.id)) + 1
    : 1;

  const filePath = `apps/${idea.slug}.md`;
  const dateAdded = idea.dateAdded || new Date().toISOString().split('T')[0];

  const entry = [
    '',
    `## Idea #${nextId}: ${idea.name}`,
    `- **File Path**: \`${filePath}\``,
    `- **Category**: ${idea.category || 'Uncategorized'}`,
    `- **Status**: Idea Generated`,
    `- **Date Added**: ${dateAdded}`,
    '',
  ].join('\n');

  let dbContent = '';

  if (existsSync(dbPath)) {
    dbContent = readFileSync(dbPath, 'utf-8');
    dbContent = dbContent.replace(
      /## Total Ideas Generated: \d+/,
      `## Total Ideas Generated: ${nextId}`
    );
    dbContent = dbContent.replace(
      /\*Last Updated: .+\*/,
      `*Last Updated: ${dateAdded}*`
    );
  } else {
    dbContent = [
      '# App Idea Database',
      `*Last Updated: ${dateAdded}*`,
      '',
      `## Total Ideas Generated: ${nextId}`,
      '',
    ].join('\n');
  }

  dbContent += entry;
  writeFileSync(dbPath, dbContent);
}

/**
 * Append a completed project entry to the projects-db.md registry.
 *
 * @param {object} project — { slug, name, status, dateCompleted }
 * @param {string} dataDir — Absolute path to the data directory
 * @param {string} projectsDbPath — Absolute path to projects-db.md
 * @param {Function} parseProjectsDb — Parser function for existing entries
 */
function appendProjectToDb(project, dataDir, projectsDbPath, parseProjectsDb) {
  mkdirSync(dataDir, { recursive: true });

  const existing = parseProjectsDb(projectsDbPath);
  const nextId = existing.length > 0
    ? Math.max(...existing.map(e => e.id)) + 1
    : 1;

  const date = project.dateCompleted || new Date().toISOString().split('T')[0];

  const entry = [
    '',
    `## Project #${nextId}: ${project.name}`,
    `- **Slug**: \`${project.slug}\``,
    `- **Status**: ${project.status}`,
    `- **Date Completed**: ${date}`,
    '',
  ].join('\n');

  if (existsSync(projectsDbPath)) {
    let dbContent = readFileSync(projectsDbPath, 'utf-8');
    dbContent = dbContent.replace(
      /## Total Projects Built: \d+/,
      `## Total Projects Built: ${nextId}`
    );
    dbContent = dbContent.replace(
      /\*Last Updated: .+\*/,
      `*Last Updated: ${date}*`
    );
    dbContent += entry;
    writeFileSync(projectsDbPath, dbContent);
  } else {
    const header = [
      '# Project Database',
      `*Last Updated: ${date}*`,
      '',
      `## Total Projects Built: ${nextId}`,
      '',
    ].join('\n');
    writeFileSync(projectsDbPath, header + entry);
  }
}

export { writeAppFile, appendToDatabase, appendProjectToDb };
